'use strict';

import React, { Component } from 'react';

import Circle from './styled/Circle';
import MarginWrapper from './styled/MarginWrapper';
import TableWrapper from './styled/TableWrapper';

import generateArray from '../helpers';

export class SquareRenderer extends Component {

  /**
   * Basically it maps the two dimension array generated by generateBiDimensionalArray and it generates as many tr as
   * X dimensions are in the array, then it maps again and it generates as many td as Y dimensions are in the array.
   *
   * Inside every td printed it prints the Circle component
   * @returns {XML}
   */
  renderCircles = () => {
    return (
      <TableWrapper>
        <tbody>
        {
          generateArray().map( (row, indexRow) => {
            return (
              <tr key={indexRow}>
                {generateArray().map( (cell, indexCell) => {
                  return (<td key={indexCell}><Circle/></td>)
                })}
              </tr>
            )
          })
        }
        </tbody>
      </TableWrapper>
    );
  };

  render = () => {
    return (
      <MarginWrapper>{this.renderCircles()}</MarginWrapper>
    );
  }

}

export default  SquareRenderer;